### ISSUE TITLE
多行显示省略符

### ISSUE THREAD

**Issue by AliasT** [AliasT/blog#15]
```css
p {
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    overflow: hidden;
}
```
