### ISSUE TITLE
未知宽高元素水平垂直居中

### ISSUE THREAD

**Issue by AliasT** [AliasT/blog#16]
1. `inline-block`, `vertical-align`
```html
<div class="container">
  <textarea></textarea>
</div>
```

```scss
.container {
  width: 500px;
  height: 500px;
  
  textarea {
    vertical-align: middle;
  }

  &:after {
    content: ' ';
    display: inline-block;
    vertical-align: middle;
    height: 100%;
  }
}
```
